import tkinter
# This file was purely generated by AI, just to have simple splash screen

def show_splash_screen():
    splash = tkinter.Tk()

    splash.overrideredirect(True)
    transparent_bg_color = "#ff00ff"
    splash.config(bg=transparent_bg_color)
    splash.wm_attributes('-transparentcolor', transparent_bg_color)
    splash.wm_attributes('-topmost', True)

    try:

        logo_img = tkinter.PhotoImage(file="resources/agent_icon.png")

        label = tkinter.Label(splash, image=logo_img, bg=transparent_bg_color, bd=0)
        label.pack()

        splash.update_idletasks()
        width = splash.winfo_reqwidth()
        height = splash.winfo_reqheight()
        x = (splash.winfo_screenwidth() // 2) - (width // 2)
        y = (splash.winfo_screenheight() // 2) - (height // 2)
        splash.geometry(f'{width}x{height}+{x}+{y}')

    except Exception as e:
        print(f"Error while loading the picture: {e}")
        splash.destroy()
        return

    splash.after(2000, splash.destroy)

    splash.mainloop()